openapi: 3.2.0
info:
  title: DeBank Open App Protocol API
  version: '1.0'
  description: Build for DeFi Developers.
servers:
- url: /
security:
- accessKey: []
tags:
- name: App Protocol
  description: Get app info
paths:
  /v1/app_protocol/list:
    get:
      responses:
        '200':
          description: return app protocol list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/App%20Protocol'
      description: Get list of apps on supported app chains
      operationId: get_app_protocol_list
      tags:
      - App Protocol
components:
  securitySchemes:
    accessKey:
      type: apiKey
      in: header
      name: AccessKey
