openapi: 3.2.0
info:
  title: DeBank Open Official API
  version: '1.0'
  description: Build for DeFi Developers.
servers:
- url: /
security:
- accessKey: []
tags:
- name: official
paths:
  /v1/official/group_send:
    post:
      responses:
        '200':
          description: Success
      operationId: post_group_send_api_view
      tags:
      - official
  /v1/official/message/send:
    post:
      responses:
        '200':
          description: Success
      operationId: post_message_send_api_view
      tags:
      - official
components:
  securitySchemes:
    accessKey:
      type: apiKey
      in: header
      name: AccessKey
